repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/python-poetry/poetry
    rev: 31657e
    hooks:
    -   id: poetry-lock
        files: (pyproject\.toml|poetry\.lock])$
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy --strict
        language: python
        types: [python]
